/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import ViewModel.ClinicaViewModel;
/**
 *
 * @author Juan Osorio
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private ClinicaViewModel viewModel;
    /**
     * Creates new form VentanaPri
     */
    public VentanaPrincipal(String rol) {
        initComponents();
        setSize(900, 600);
        setLocationRelativeTo(null);
        panelContenido.setLayout(new java.awt.CardLayout());
        setTitle("Bienvenido, " + rol);
        setVisible(true);
        viewModel = new ClinicaViewModel(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        btnVerHistorialPacientes = new javax.swing.JButton();
        btnVerConsultasMedico = new javax.swing.JButton();
        btnAsignarConsultas = new javax.swing.JButton();
        btnRegistroMedicos = new javax.swing.JButton();
        btnRegistroPacientes = new javax.swing.JButton();
        panelContenido = new javax.swing.JPanel();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnVerHistorialPacientes.setText("Ver Historial Del Paciente");

        btnVerConsultasMedico.setText("Ver Consultas Por Medico");

        btnAsignarConsultas.setText("Asignar Consulta");
        btnAsignarConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarConsultasActionPerformed(evt);
            }
        });

        btnRegistroMedicos.setText("Registrar Medico");
        btnRegistroMedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroMedicosActionPerformed(evt);
            }
        });

        btnRegistroPacientes.setText("Registrar Paciente");
        btnRegistroPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroPacientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnVerConsultasMedico)
                        .addComponent(btnVerHistorialPacientes))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegistroMedicos)
                            .addComponent(btnAsignarConsultas)
                            .addComponent(btnRegistroPacientes))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegistroPacientes)
                .addGap(18, 18, 18)
                .addComponent(btnRegistroMedicos)
                .addGap(18, 18, 18)
                .addComponent(btnAsignarConsultas)
                .addGap(18, 18, 18)
                .addComponent(btnVerHistorialPacientes)
                .addGap(18, 18, 18)
                .addComponent(btnVerConsultasMedico)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );
        panelContenidoLayout.setVerticalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroPacientesActionPerformed
        PanelRegistro panel = new PanelRegistro(viewModel);
        panelContenido.add(panel, "registro Paciente.");
        
        java.awt.CardLayout cl = (java.awt.CardLayout) panelContenido.getLayout();
        cl.show(panelContenido, "Registro paciente.");
    }//GEN-LAST:event_btnRegistroPacientesActionPerformed

    private void btnRegistroMedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroMedicosActionPerformed
        PanelRegistro panel = new PanelRegistro(viewModel);
        panelContenido.add(panel, "registro Medico.");
        
        java.awt.CardLayout cl = (java.awt.CardLayout) panelContenido.getLayout();
        cl.show(panelContenido, "Registro Medico.");
    }//GEN-LAST:event_btnRegistroMedicosActionPerformed

    private void btnAsignarConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarConsultasActionPerformed
        panelContenido.removeAll();
        panelContenido.add(new PanelConsulta(viewModel));
        panelContenido.revalidate();
        panelContenido.repaint();
    }//GEN-LAST:event_btnAsignarConsultasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */   
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal("admin").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarConsultas;
    private javax.swing.JButton btnRegistroMedicos;
    private javax.swing.JButton btnRegistroPacientes;
    private javax.swing.JButton btnVerConsultasMedico;
    private javax.swing.JButton btnVerHistorialPacientes;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelContenido;
    // End of variables declaration//GEN-END:variables
}
