/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import ViewModel.ClinicaViewModel;
import view.PanelConsulta;
import view.PanelRegistro;
/**
 *
 * @author Juan Osorio
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private ClinicaViewModel viewModel;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal(String rol) {
        initComponents();
        setSize(900, 600);
        setLocationRelativeTo(null);
        panelContenido.setLayout(new java.awt.CardLayout());
        setTitle("Bienvenido, " + rol);
        setVisible(true);
        viewModel = new ClinicaViewModel(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistroPaciente = new javax.swing.JButton();
        btnRegistroMedico = new javax.swing.JButton();
        btnAsignarConsulta = new javax.swing.JButton();
        btnVerHistorialPaciente = new javax.swing.JButton();
        btnVerConsultasMedico = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        panelContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRegistroPaciente.setText("Registrar Paciente");
        btnRegistroPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroPacienteActionPerformed(evt);
            }
        });

        btnRegistroMedico.setText("Registar Medico");
        btnRegistroMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroMedicoActionPerformed(evt);
            }
        });

        btnAsignarConsulta.setText("Asignar Consulta");
        btnAsignarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarConsultaActionPerformed(evt);
            }
        });

        btnVerHistorialPaciente.setText("Ver Historial Del Paciente");
        btnVerHistorialPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerHistorialPacienteActionPerformed(evt);
            }
        });

        btnVerConsultasMedico.setText("Ver Consultas Por Medico");

        jPanel2.setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );
        panelContenidoLayout.setVerticalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnVerConsultasMedico)
                        .addComponent(btnVerHistorialPaciente))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnAsignarConsulta)
                                .addComponent(btnRegistroMedico))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(btnRegistroPaciente)))))
                .addGap(18, 18, 18)
                .addComponent(panelContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRegistroPaciente)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRegistroMedico)
                                .addGap(25, 25, 25)
                                .addComponent(btnAsignarConsulta)
                                .addGap(25, 25, 25)
                                .addComponent(btnVerHistorialPaciente))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(btnVerConsultasMedico)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroPacienteActionPerformed
        PanelRegistro panel = new PanelRegistro(viewModel);
        panelContenido.add(panel, "registro Paciente.");
        
        java.awt.CardLayout cl = (java.awt.CardLayout) panelContenido.getLayout();
        cl.show(panelContenido, "Registro paciente.");
    }//GEN-LAST:event_btnRegistroPacienteActionPerformed

    private void btnRegistroMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroMedicoActionPerformed
        PanelRegistro panel = new PanelRegistro(viewModel);
        panelContenido.add(panel, "registro Medico.");
        
        java.awt.CardLayout cl = (java.awt.CardLayout) panelContenido.getLayout();
        cl.show(panelContenido, "Registro Medico.");
    }//GEN-LAST:event_btnRegistroMedicoActionPerformed

    private void btnAsignarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarConsultaActionPerformed
        panelContenido.removeAll();
        panelContenido.add(new PanelConsulta(viewModel));
        panelContenido.revalidate();
        panelContenido.repaint();
    }//GEN-LAST:event_btnAsignarConsultaActionPerformed

    private void btnVerHistorialPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerHistorialPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerHistorialPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal("admin").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarConsulta;
    private javax.swing.JButton btnRegistroMedico;
    private javax.swing.JButton btnRegistroPaciente;
    private javax.swing.JButton btnVerConsultasMedico;
    private javax.swing.JButton btnVerHistorialPaciente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelContenido;
    // End of variables declaration//GEN-END:variables
}
